### ISSUE TITLE
Multiprocess monitoring

### ISSUE THREAD

**Issue by erikcw** [dkruchinin/sanic-prometheus#3]
If running Sanic in multi-worker mode (ie `app.run(workers=...)`), it appears that we run into an issue documented in the [prometheus_client README](https://github.com/prometheus/client_python/blob/master/README.md#multiprocess-mode-gunicorn) titled "Multiprocess Mode".

If I repeatedly refresh the /metrics end point in my dev environment after hitting some endpoints a few times, the output will "rotate" between the correct metrics and blank or underreported metrics.  I'm guessing the underreported/blank metrics are from worker processes that haven't served requests yet.

I'm guessing `multiprocess_mode` should be added to the various sanic-prometheus metrics.

**Comment by dkruchinin** [comment]
Hey @erikcw,
I'll see what I can do with it.
Thanks for reporting 🙏

**Comment by dkruchinin** [comment]
@erikcw 
Hey, I have some good and bad news.

Good news: I finally added multiprocessing support to `sanic_prometheus` (see `multiprocessing` branch). 

Bad news: It doesn't work :) Unfortunately multiprocessing is broken in `prometheus_client` at the moment (see https://github.com/prometheus/client_python/pull/173 for more details). There's a PR that seems to fix the bug (https://github.com/prometheus/client_python/pull/169) but it hasn't been merged yet.

I'll do a release as soon as the problem get fixed in `prometheus_cleint`.

**Comment by dkruchinin** [comment]
@erikcw https://github.com/prometheus/client_python/pull/169 finally got merged to master, so it's ready to use. As it hasn't been released yet, in order to use it you'll have to build the latest version of ``python_client`` manually along with ``sanic_prometheus`` from ``multiprocessing`` branch. I added instructions of how to use it in multiprocess mode to README. Alternatively you can wait for an official release.

Anyway, let me know if it works for you.

**Comment by dkruchinin** [comment]
Multiprocessing support is available in a new **0.1.4** release.
